g = 5
p = 97
a = 32
b = 41

# Calculando A y B
A = (g ** a) % p
B = (g ** b) % p

# Calculando la clave compartida
skeyA = (B ** a) % p
skeyB = (A ** b) % p

print("A (Alice's value):", A)
print("B (Bob's value):", B)
print("Shared key generated by Alice:", skeyA)
print("Shared key generated by Bob:", skeyB)